### ISSUE TITLE
Implement remaining Jazzband guidelines for wagtailmenus

### ISSUE THREAD

**Issue by MrCordeiro** [jazzband/wagtailmenus#411]
I opened this new issue to keep track of the remaining tasks. I plan to work on this weekend, but anyone should feel free to pitch in.

- [x] Fix all links in the docs (and README file etc) from old to new repo
- [x] Fix project URL in [GitHub project](https://github.com/jazzband/wagtailmenus) description
- [x] Remove Transifex service for translations (according to #409)

**Comment by MrCordeiro** [comment]
@jezdez , I'm having some issues trying to publish the remaining changes (I'm getting a 500 error). I have no previous experience with GitHub Actions or pypa. Is there any issues with the Release yml?

```
name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'jazzband/wagtailmenus'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel
      - name: Build package
        run: |
          python setup.py --version
          python setup.py sdist --format=gztar bdist_wheel
          twine check dist/*
      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/wagtailmenus/upload 
```
